### ISSUE TITLE
Build error: Failed to install 'com.rjfun.cordova.mmedia'

### ISSUE THREAD

**Issue by snowuyl** [floatinghotpot/cordova-plugin-mmedia#1]
Dear Floatinghotpot,

I follow the following command to create mMedia plug-in. But build error. Please help to give suggestion to solve this issue. Thanks in advance. The following is build log message.

```
Error during processing of action! Attempting to revert...
Failed to install 'com.rjfun.cordova.mmedia':Error: Uh oh!
"/Users/snowuyl/Documents/workspace2/Boutique/platforms/android/libs/MMSDK.jar" already exists!
```

**Comment by floatinghotpot** [comment]
I've simplified your issue by picking the key error message.

It's a bug in plugin.xml, and now fixed, please remove the plugin and try again.

**Comment by snowuyl** [comment]
It works. Thanks for your great help.
