### ISSUE TITLE
IOS Interstitial Not Working

### ISSUE THREAD

**Issue by appsoftba2** [floatinghotpot/cordova-plugin-mmedia#13]
Banner ads looks fine but interstitial ads are not fetching from server.  In Debug mode the error mesage is like this:

mMedia, onAdfailload,  adnetwork:mmedia,   adtype:interstitial , adevent:onadfailload, error:-500 , reason: caching unsuccesful.

 So it cant cache and store the interstitial ads, even test ads. try in iphone3s, iphone4s,iphone6 and simulators. All the same. 

 If someone else can get an interstitial, my second guess is i'M still using xcode 6.2 due to being a poor bad boy with a hackintosh. I'm not sure about the reason but i definetly hit a big wall.  HELP ME PLEASE MY BEST CORDOVA PLUGIN FRIEND !

**Comment by floatinghotpot** [comment]
The banner and interstitial both worked, at least when this plugin was published. 

My mmedia account was disabled quite long time ago, as I did not use it much, I asked mMedia for support, but they have no response. Without a useable account, I cannot verify what's happening. 

Do you have to use the mMedia?

**Comment by appsoftba2** [comment]
Well, no i guess. trying other networks now. thanks for your quick response.

**Comment by floatinghotpot** [comment]
According to my personal experience, try: AdMob, Flurry, FacebookAds, they support very well, good fill rate, and pay on time.
