### ISSUE TITLE
Three errors when import cordova-plugin-mmedia APK source to ADT

### ISSUE THREAD

**Issue by snowuyl** [floatinghotpot/cordova-plugin-mmedia#14]
Dear floatinghotpot,

```
   I type the following commands to generate cordova-plugin-mmedia APK
```

cordova create mmedia com.snowuyl.mmedia mmedia
cd mmedia
cordova platform add android
cordova plugin add cordova-plugin-mmedia
cordova build

Then I import cordova-plugin-mmedia APK source to ADT.
But the following three errors occur.
1. AndroidManifest.xml file missing!    MainActivity        Unknown Android Packaging Problem
2. The project was not built since its build path is incomplete. Cannot find the class file for org.apache.cordova.CallbackContext. Fix the build path then try building this project   MainActivity        Unknown Java Problem
3. Description  Resource    Path    Location    Type
The type org.apache.cordova.CallbackContext cannot be resolved. It is indirectly referenced from required .class files  mMediaAdPlugin.java /MainActivity/src/com/rjfun/cordova/mmedia  line 1  Java Problem

Do I need to import cordova-plugin-mmedia APK source to Android Studio instead ADT?

Thanks in advance.

snowuyl

**Comment by snowuyl** [comment]
I have fixing this issue by importing cordova-plugin-mmedia APK source to Android Studio

**Comment by floatinghotpot** [comment]
Yes, not only this plugin, it's a common issue for Cordova project. The default project file is for Android Studio, not eclipse any more.
