### ISSUE TITLE
Plugin requires record permissions on Android

### ISSUE THREAD

**Issue by pantonis** [floatinghotpot/cordova-plugin-mmedia#8]
Hi,

I dont understand why a plugin that shows ads needs to record audio. Is this a bug?

**Comment by floatinghotpot** [comment]
It's required by mMedia SDK, as the plugin is implemented based on the SDK. You can visit mMedia SDK for more details.

**Comment by pantonis** [comment]
I have spoken with MMedia. They said that the audio is optional. Below is their reply
"Glad to hear it's working! That's a good question-- The RECORD_AUDIO permission is optional. If your app doesn't need it, simply don't include it. We used it for interactive voice ads."

Can we have a branch that does not include this?

**Comment by jmelvin** [comment]
Indeed, I'm asking MMedia the same questions about several permissions...

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_CALENDAR"/>
<uses-permission android:name="android.permission.NFC"/>
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
```

Without knowing more, I was going to try and post-process the AndroidManifest.xml file to remove these permissions before cordova build.  It may or may not be possible.
